data = [
{"date":"2026-03-01","route_name":"Morning Slab","grade":"5B","place":"Local Gym","num_tries":"1","note":"Easy warmup","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-03-01","route_name":"Pocket Start","grade":"5C","place":"Local Gym","num_tries":"1","note":"Read it well","os_var":False,"flash_var":True,"rp_var":False,"photo_path": None},
{"date":"2026-03-01","route_name":"Pinch Ladder","grade":"6A","place":"Local Gym","num_tries":"3","note":"Needed better body position","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-03-04","route_name":"Grey Balance","grade":"5C","place":"Climb Zone","num_tries":"1","note":"Nice slab","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-03-04","route_name":"Sloper Garden","grade":"6B","place":"Climb Zone","num_tries":"4","note":"Slopers were tough","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-03-04","route_name":"Roof Start","grade":"6C","place":"Climb Zone","num_tries":"2","note":"Still projecting","os_var":False,"flash_var":False,"rp_var":False,"photo_path": None},

{"date":"2026-03-08","route_name":"Forest Warmup","grade":"5C","place":"Sandstone Crag","num_tries":"1","note":"Perfect friction","os_var":False,"flash_var":True,"rp_var":False,"photo_path": None},
{"date":"2026-03-08","route_name":"Pocket Tower","grade":"6A+","place":"Sandstone Crag","num_tries":"3","note":"Fun pockets","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-03-08","route_name":"Thin Edge","grade":"6C","place":"Sandstone Crag","num_tries":"5","note":"Small crimps","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-03-12","route_name":"Yellow Flow","grade":"5B","place":"Local Gym","num_tries":"1","note":"Smooth climbing","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-03-12","route_name":"Compression Fun","grade":"6B","place":"Local Gym","num_tries":"1","note":"Friend showed beta","os_var":False,"flash_var":True,"rp_var":False,"photo_path": None},
{"date":"2026-03-12","route_name":"Crimp Ladder","grade":"6C+","place":"Local Gym","num_tries":"6","note":"Hard crux move","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-03-16","route_name":"Granite Slab","grade":"5C+","place":"Granite Valley","num_tries":"1","note":"Very friction dependent","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-03-16","route_name":"Granite Arete","grade":"6A+","place":"Granite Valley","num_tries":"2","note":"Balance problem","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-03-16","route_name":"Granite Roof","grade":"6C+","place":"Granite Valley","num_tries":"4","note":"Powerful climbing","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-03-20","route_name":"Morning Circuit","grade":"5B+","place":"Climb Zone","num_tries":"1","note":"Warmup lap","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-03-20","route_name":"Heel Hook Line","grade":"6A","place":"Climb Zone","num_tries":"1","note":"Got beta first","os_var":False,"flash_var":True,"rp_var":False,"photo_path": None},
{"date":"2026-03-20","route_name":"Steep Crux","grade":"6C","place":"Climb Zone","num_tries":"7","note":"Finally sent","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-03-25","route_name":"Hidden Pocket","grade":"6A","place":"Sandstone Crag","num_tries":"1","note":"Surprisingly easy","os_var":False,"flash_var":True,"rp_var":False,"photo_path": None},
{"date":"2026-03-25","route_name":"Edge Traverse","grade":"6B+","place":"Sandstone Crag","num_tries":"4","note":"Good endurance","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-03-25","route_name":"Tall Arete","grade":"7A","place":"Sandstone Crag","num_tries":"3","note":"Still working it","os_var":False,"flash_var":False,"rp_var":False,"photo_path": None},

{"date":"2026-03-28","route_name":"Sunset Slab","grade":"5A","place":"Local Gym","num_tries":"2","note":"Gentle slab with good holds","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-03-28","route_name":"Crux Wall","grade":"6C","place":"Climb Zone","num_tries":"3","note":"Powerful crux moves","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-03-28","route_name":"Pocket Traverse","grade":"6B+","place":"Sandstone Crag","num_tries":"2","note":"Fun endurance problem","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-03-30","route_name":"The Chimney","grade":"6A","place":"Granite Valley","num_tries":"3","note":"Steep but juggy","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-03-30","route_name":"Slab Delight","grade":"5C","place":"Granite Valley","num_tries":"1","note":"Nice friction footwork","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-03-30","route_name":"Overhang Puzzle","grade":"6C+","place":"New Boulder Park","num_tries":"5","note":"Powerful moves on crimps","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-04-02","route_name":"Arete Adventure","grade":"6B","place":"New Boulder Park","num_tries":"3","note":"Technical and fun","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-04-02","route_name":"Sloper Heaven","grade":"6C","place":"Climb Zone","num_tries":"4","note":"Lots of sloper work","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-04-02","route_name":"Warmup Crack","grade":"5B","place":"Sandstone Crag","num_tries":"1","note":"Perfect start for the day","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},

{"date":"2026-04-05","route_name":"Dynamic Roof","grade":"7A","place":"Granite Valley","num_tries":"6","note":"Big dynamic moves","os_var":False,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-04-05","route_name":"Finger Crimps","grade":"6C+","place":"Local Gym","num_tries":"5","note":"Small crimps challenge","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-04-05","route_name":"Easy Flow","grade":"5A","place":"Climb Zone","num_tries":"1","note":"Smooth climbing and fun","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},

{"date":"2026-04-10","route_name":"Skyline Arete","grade":"7B","place":"Granite Valley","num_tries":"4","note":"Sustained moves with good crimps","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-04-10","route_name":"Slab Master","grade":"6C","place":"Local Gym","num_tries":"2","note":"Technical slab, tricky footwork","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-04-10","route_name":"Pocket Roof","grade":"7A+","place":"Sandstone Crag","num_tries":"5","note":"Big roof, powerful pockets","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-04-12","route_name":"Crimp Marathon","grade":"7C","place":"New Boulder Park","num_tries":"6","note":"Small crimps, endurance test","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-04-12","route_name":"Balance Beam","grade":"6B+","place":"Climb Zone","num_tries":"1","note":"Slab with subtle balance moves","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-04-12","route_name":"Dynamic Flight","grade":"7B+","place":"Granite Valley","num_tries":"3","note":"Dynamic sequences on steep wall","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-04-15","route_name":"Overhang Nightmare","grade":"8A","place":"New Boulder Park","num_tries":"8","note":"Powerful overhangs, tough crux","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-04-15","route_name":"Finger Locks","grade":"7A","place":"Local Gym","num_tries":"4","note":"Sustained finger strength needed","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-04-15","route_name":"Sloper Paradise","grade":"6C+","place":"Climb Zone","num_tries":"2","note":"Slopers galore, endurance test","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-04-18","route_name":"The Pinnacle","grade":"8B","place":"Granite Valley","num_tries":"10","note":"Long route with multiple cruxes","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-04-18","route_name":"Crack Delight","grade":"6B","place":"Sandstone Crag","num_tries":"3","note":"Fun crack climbing, perfect technique","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-04-18","route_name":"Roof Chaos","grade":"7C+","place":"New Boulder Park","num_tries":"7","note":"Powerful roof moves, tricky footwork","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-04-20","route_name":"Endurance Wall","grade":"7B","place":"Climb Zone","num_tries":"5","note":"Continuous moves with minimal rests","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-04-20","route_name":"Tech Slab","grade":"6C","place":"Local Gym","num_tries":"2","note":"Delicate footwork required","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-04-20","route_name":"Pocket Overhang","grade":"7A+","place":"Sandstone Crag","num_tries":"4","note":"Overhang with small pockets","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-04-25","route_name":"Ultimate Arete","grade":"8C+","place":"Granite Valley","num_tries":"12","note":"Peak performance required, extreme route","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-04-25","route_name":"Slab Sprint","grade":"5A+","place":"Climb Zone","num_tries":"1","note":"Quick warmup slab","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-04-25","route_name":"Thin Edge Plus","grade":"7B+","place":"New Boulder Park","num_tries":"5","note":"Small edges, sustained","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-05-01","route_name":"Easy Morning Slab","grade":"5A","place":"Local Gym","num_tries":"1","note":"Gentle warmup slab","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-05-01","route_name":"Smooth Flow","grade":"5B","place":"Local Gym","num_tries":"1","note":"Nice flowing movements","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-05-01","route_name":"Pocket Climb","grade":"5C","place":"Sandstone Crag","num_tries":"2","note":"Fun pockets, easy","os_var":False,"flash_var":True,"rp_var":False,"photo_path": None},

{"date":"2026-05-05","route_name":"Crimp Ladder","grade":"6A","place":"Climb Zone","num_tries":"3","note":"Slightly harder crimps","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-05","route_name":"Sloper Wall","grade":"6A+","place":"Local Gym","num_tries":"2","note":"Slopers, need balance","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-05","route_name":"Technical Slab","grade":"6B","place":"Granite Valley","num_tries":"3","note":"Delicate footwork","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-05-06","route_name":"Pocket Overhang","grade":"6B+","place":"Sandstone Crag","num_tries":"4","note":"Small pockets, overhang","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-06","route_name":"Steep Arete","grade":"6C","place":"New Boulder Park","num_tries":"5","note":"Continuous moves on arete","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-06","route_name":"Crimp Challenge","grade":"6C+","place":"Climb Zone","num_tries":"6","note":"Long crimp section","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-05-10","route_name":"Dynamic Roof","grade":"7A","place":"Granite Valley","num_tries":"5","note":"Powerful roof moves","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-10","route_name":"Technical Overhang","grade":"7A+","place":"New Boulder Park","num_tries":"6","note":"Sustained overhang moves","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-10","route_name":"Balance Arete","grade":"7B","place":"Climb Zone","num_tries":"5","note":"Balance and precision required","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-11","route_name":"Crimp Marathon","grade":"7B+","place":"Sandstone Crag","num_tries":"6","note":"Small crimps, endurance test","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-11","route_name":"Sloper Heaven","grade":"7C","place":"Granite Valley","num_tries":"7","note":"Slopers and dynamic moves","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-11","route_name":"Roof Puzzle","grade":"7C+","place":"New Boulder Park","num_tries":"8","note":"Complex roof, tricky footwork","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-05-15","route_name":"Overhang Nightmare","grade":"8A","place":"Granite Valley","num_tries":"10","note":"Extreme overhang moves","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-15","route_name":"Finger Crimps","grade":"8A+","place":"New Boulder Park","num_tries":"9","note":"Sustained finger strength needed","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-15","route_name":"The Pinnacle","grade":"8B","place":"Sandstone Crag","num_tries":"11","note":"Multiple cruxes","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-16","route_name":"Ultimate Arete","grade":"8B+","place":"Granite Valley","num_tries":"12","note":"Peak performance required","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-16","route_name":"Roof Chaos","grade":"8C","place":"New Boulder Park","num_tries":"13","note":"Powerful roof sequence","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-05-20","route_name":"Legend Wall","grade":"9A","place":"Granite Valley","num_tries":"15","note":"Elite level, extremely hard","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-20","route_name":"Crux Supreme","grade":"9A","place":"New Boulder Park","num_tries":"14","note":"Only for top climbers","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-20","route_name":"Ultimate Overhang","grade":"9A","place":"Sandstone Crag","num_tries":"16","note":"Maximum power and endurance","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-05-01","route_name":"Easy Slab","grade":"5A","place":"Local Gym","num_tries":"1","note":"Gentle warmup slab","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-05-01","route_name":"Pocket Flow","grade":"5B","place":"Local Gym","num_tries":"1","note":"Smooth pockets, easy","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-05-02","route_name":"Balance Beam","grade":"5C","place":"Climb Zone","num_tries":"2","note":"Good balance practice","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},

{"date":"2026-05-03","route_name":"Crimp Ladder","grade":"6A","place":"Sandstone Crag","num_tries":"2","note":"Slightly harder crimps","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-03","route_name":"Sloper Wall","grade":"6A+","place":"Local Gym","num_tries":"3","note":"Slopers require balance","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-04","route_name":"Technical Slab","grade":"6B","place":"Granite Valley","num_tries":"3","note":"Delicate footwork","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-05-04","route_name":"Pocket Overhang","grade":"6B+","place":"Sandstone Crag","num_tries":"4","note":"Small pockets, moderate overhang","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-05","route_name":"Steep Arete","grade":"6C","place":"New Boulder Park","num_tries":"4","note":"Continuous moves on arete","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-05","route_name":"Crimp Challenge","grade":"6C+","place":"Climb Zone","num_tries":"5","note":"Sustained crimps, moderate difficulty","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-05-08","route_name":"Dynamic Roof","grade":"7A","place":"Granite Valley","num_tries":"5","note":"Powerful roof moves","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-08","route_name":"Technical Overhang","grade":"7A+","place":"New Boulder Park","num_tries":"6","note":"Sustained overhang moves","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-09","route_name":"Balance Arete","grade":"7B","place":"Climb Zone","num_tries":"6","note":"Balance and precise footwork","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-09","route_name":"Crimp Marathon","grade":"7B+","place":"Sandstone Crag","num_tries":"7","note":"Endurance on small crimps","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-10","route_name":"Sloper Heaven","grade":"7C","place":"Granite Valley","num_tries":"8","note":"Slopers and dynamic sequences","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-10","route_name":"Roof Puzzle","grade":"7C+","place":"New Boulder Park","num_tries":"8","note":"Challenging roof, tricky footwork","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-05-12","route_name":"Overhang Test","grade":"8A","place":"Granite Valley","num_tries":"9","note":"Powerful overhang moves, few can send easily","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-12","route_name":"Finger Strength","grade":"8A+","place":"New Boulder Park","num_tries":"9","note":"Sustained finger strength challenge","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-12","route_name":"Pinnacle Arete","grade":"8B","place":"Sandstone Crag","num_tries":"10","note":"Multi-crux route, endurance test","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-13","route_name":"Ultimate Roof","grade":"8B+","place":"Granite Valley","num_tries":"11","note":"Long, sustained roof sequence","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-13","route_name":"Power Overhang","grade":"8C","place":"New Boulder Park","num_tries":"12","note":"Elite-level overhang, very few can send","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

{"date":"2026-05-01","route_name":"Easy Slab","grade":"5A+","place":"Local Gym","num_tries":"1","note":"Gentle warmup slab","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-05-01","route_name":"Pocket Flow","grade":"5B+","place":"Local Gym","num_tries":"1","note":"Smooth pockets, easy","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-05-02","route_name":"Balance Beam","grade":"5C","place":"Climb Zone","num_tries":"2","note":"Good balance practice","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-05-03","route_name":"Crimp Ladder","grade":"6A","place":"Sandstone Crag","num_tries":"2","note":"Slightly harder crimps","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-03","route_name":"Steep Arete","grade":"6C","place":"New Boulder Park","num_tries":"4","note":"Continuous moves on arete","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-04","route_name":"Pocket Overhang","grade":"6B+","place":"Sandstone Crag","num_tries":"4","note":"Small pockets, moderate overhang","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-04","route_name":"Technical Slab","grade":"6B","place":"Granite Valley","num_tries":"3","note":"Delicate footwork","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-05-05","route_name":"Crimp Challenge","grade":"6C+","place":"Climb Zone","num_tries":"5","note":"Sustained crimps, moderate difficulty","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-05","route_name":"Sloper Wall","grade":"6A+","place":"Local Gym","num_tries":"3","note":"Slopers require balance","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-08","route_name":"Dynamic Roof","grade":"7A","place":"Granite Valley","num_tries":"5","note":"Powerful roof moves","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-08","route_name":"Technical Overhang","grade":"7A+","place":"New Boulder Park","num_tries":"6","note":"Sustained overhang moves","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-09","route_name":"Balance Arete","grade":"7B","place":"Climb Zone","num_tries":"6","note":"Balance and precise footwork","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-09","route_name":"Crimp Marathon","grade":"7B+","place":"Sandstone Crag","num_tries":"7","note":"Endurance on small crimps","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-10","route_name":"Sloper Heaven","grade":"7C","place":"Granite Valley","num_tries":"8","note":"Slopers and dynamic sequences","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-10","route_name":"Roof Puzzle","grade":"7C+","place":"New Boulder Park","num_tries":"8","note":"Challenging roof, tricky footwork","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-12","route_name":"Overhang Test","grade":"8A","place":"Granite Valley","num_tries":"9","note":"Powerful overhang moves, few can send easily","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-12","route_name":"Finger Strength","grade":"8A+","place":"New Boulder Park","num_tries":"9","note":"Sustained finger strength challenge","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-12","route_name":"Pinnacle Arete","grade":"8B","place":"Sandstone Crag","num_tries":"10","note":"Multi-crux route, endurance test","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-13","route_name":"Ultimate Roof","grade":"8B+","place":"Granite Valley","num_tries":"11","note":"Long, sustained roof sequence","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-13","route_name":"Power Overhang","grade":"8C","place":"New Boulder Park","num_tries":"12","note":"Elite-level overhang, very few can send","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-15","route_name":"Morning Slab","grade":"5C","place":"Local Gym","num_tries":"1","note":"Warmup for the day","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-05-15","route_name":"Crux Wall","grade":"7B","place":"Granite Valley","num_tries":"4","note":"Powerful crux section","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-16","route_name":"Slab Sprint","grade":"5B","place":"Climb Zone","num_tries":"1","note":"Quick warmup","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-05-16","route_name":"Pocket Traverse","grade":"6B+","place":"Sandstone Crag","num_tries":"3","note":"Endurance on pockets","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-17","route_name":"Thin Edge Plus","grade":"7B+","place":"New Boulder Park","num_tries":"5","note":"Small crimps, sustained","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-17","route_name":"Sunset Slab","grade":"5A+","place":"Local Gym","num_tries":"1","note":"Evening warmup slab","os_var":True,"flash_var":False,"rp_var":False,"photo_path": None},
{"date":"2026-05-18","route_name":"Crimp Ladder","grade":"6C","place":"Climb Zone","num_tries":"5","note":"Hard crux section","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},
{"date":"2026-05-18","route_name":"Dynamic Flight","grade":"7B+","place":"Granite Valley","num_tries":"6","note":"Dynamic sequences on steep wall","os_var":False,"flash_var":False,"rp_var":True,"photo_path": None},

]